from __future__ import annotations

from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from .models import FilterClause, Target


@runtime_checkable
class Dataset(Protocol):
    def filter(self, clauses: Iterable[FilterClause]) -> "Dataset": ...
    def select(self, cols: Iterable[str]) -> "Dataset": ...
    def head(self, n: int) -> Any: ...
    def collect(self) -> Any: ...
    def sink(self, path: Path) -> None: ...
    def schema(self) -> Mapping[str, str]: ...
    def columns(self) -> list[str]: ...


@runtime_checkable
class QueryEngine(Protocol):
    def supports(self, path: Path) -> bool: ...
    def open(self, path: Path) -> Dataset: ...
    def concat(self, datasets: Iterable[Dataset]) -> Dataset: ...
    def join(self, left: Dataset, right: Dataset, *,
             on: list[str], how: str = "inner") -> Dataset: ...


@runtime_checkable
class DataSource(Protocol):
    def fetch(self, target: Target, dest: Path, *, force: bool = False) -> list[Path]:
        ...


@runtime_checkable
class Storage(Protocol):
    def location(self, target: Target) -> Path: ...
    def list_targets(self, kind: str) -> list[str]: ...
    def list_files(self, target: Target) -> list[Path]: ...


@runtime_checkable
class ConfigSource(Protocol):
    def load(self) -> list[Target]: ...
